"""create phone-stock table

Revision ID: 29f58152bb99
Revises: 
Create Date: 2024-05-17 16:17:26.265307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29f58152bb99'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PhoneStock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_model', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('chip', sa.Boolean(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PhoneStock')
    # ### end Alembic commands ###
