"""create usuarios table

Revision ID: d2767bea46e4
Revises: 1b35a42eb025
Create Date: 2024-04-09 22:32:36.775697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2767bea46e4'
down_revision: Union[str, None] = '1b35a42eb025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('senha', sa.String(), nullable=False))
    op.drop_column('usuarios', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password', sa.VARCHAR(), nullable=False))
    op.drop_column('usuarios', 'senha')
    # ### end Alembic commands ###
